/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop;

/**
 *
 * @author haris
 */
public class FileExplorer extends javax.swing.JInternalFrame {

    /**
     * Creates new form FileExplorer
     */
    public FileExplorer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileExplorerPanel = new javax.swing.JPanel();
        leftPane = new javax.swing.JLabel();
        topPane = new javax.swing.JLabel();
        pdf1 = new javax.swing.JCheckBox();
        pdf2 = new javax.swing.JCheckBox();
        pdf3 = new javax.swing.JCheckBox();
        rightClickButton = new javax.swing.JButton();
        repeatButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("File Explorer");

        fileExplorerPanel.setBackground(new java.awt.Color(255, 255, 255));

        leftPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/images/leftPane.png"))); // NOI18N

        topPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/images/topPane.png"))); // NOI18N

        pdf1.setText("pdf1.pdf");

        pdf2.setText("pdf2.pdf");

        pdf3.setText("pdf3.pdf");

        rightClickButton.setBackground(new java.awt.Color(204, 204, 204));
        rightClickButton.setText("Open");
        rightClickButton.setBorder(null);
        rightClickButton.setBorderPainted(false);
        rightClickButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightClickButtonActionPerformed(evt);
            }
        });

        repeatButton.setText("Repeat Paste");
        repeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileExplorerPanelLayout = new javax.swing.GroupLayout(fileExplorerPanel);
        fileExplorerPanel.setLayout(fileExplorerPanelLayout);
        fileExplorerPanelLayout.setHorizontalGroup(
            fileExplorerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileExplorerPanelLayout.createSequentialGroup()
                .addComponent(leftPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fileExplorerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileExplorerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fileExplorerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pdf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pdf2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pdf3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(fileExplorerPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(rightClickButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(repeatButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(topPane, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        fileExplorerPanelLayout.setVerticalGroup(
            fileExplorerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileExplorerPanelLayout.createSequentialGroup()
                .addComponent(topPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fileExplorerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileExplorerPanelLayout.createSequentialGroup()
                        .addComponent(leftPane, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(fileExplorerPanelLayout.createSequentialGroup()
                        .addComponent(pdf1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pdf2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pdf3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fileExplorerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rightClickButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );

        repeatButton.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fileExplorerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileExplorerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rightClickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightClickButtonActionPerformed
        // TODO add your handling code here:

        if (pdf1.isSelected()) {
            PDF1 pdf1 = new PDF1();
            Main.desktopPane.add(pdf1);
            pdf1.setVisible(true);
        }

        if (pdf2.isSelected()) {
            PDF2 pdf2 = new PDF2();
            Main.desktopPane.add(pdf2);
            pdf2.setVisible(true);
        }

        if (pdf3.isSelected()) {
            PDF3 pdf3 = new PDF3();
            Main.desktopPane.add(pdf3);
            pdf3.setVisible(true);
        }
    }//GEN-LAST:event_rightClickButtonActionPerformed

    private void repeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatButtonActionPerformed
        // TODO add your handling code here:
        String txt = "";
        
        if (pdf1.isSelected()) {
            txt = txt + PDF1.pdf1Text;
        }
        
        if (pdf2.isSelected()) {
            txt = txt + PDF2.pdf2Text;
        }
        
        if (pdf3.isSelected()) {
            txt = txt + PDF3.pdf3Text;
        }
        
        Main.pasteMultiTitles(evt, txt);
    }//GEN-LAST:event_repeatButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fileExplorerPanel;
    private javax.swing.JLabel leftPane;
    private javax.swing.JCheckBox pdf1;
    private javax.swing.JCheckBox pdf2;
    private javax.swing.JCheckBox pdf3;
    public javax.swing.JButton repeatButton;
    private javax.swing.JButton rightClickButton;
    private javax.swing.JLabel topPane;
    // End of variables declaration//GEN-END:variables
}
