/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop;

/**
 *
 * @author haris
 */
public class PDF1 extends javax.swing.JInternalFrame {
    
    public static String pdf1Text = "Prototyping and Sampling Experience to Evaluate Ubiquitous Computing Privacy in the Real World";

    /**
     * Creates new form PDF1
     */
    public PDF1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pdf1Panel = new javax.swing.JPanel();
        pdf1TitleButton = new javax.swing.JButton();
        pd1Text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("pdf1");

        pdf1Panel.setBackground(new java.awt.Color(255, 255, 255));

        pdf1TitleButton.setBackground(new java.awt.Color(255, 255, 255));
        pdf1TitleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/images/pdf1Title.png"))); // NOI18N
        pdf1TitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdf1TitleButtonActionPerformed(evt);
            }
        });

        pd1Text.setBackground(new java.awt.Color(255, 255, 255));
        pd1Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/images/pdf1Text.png"))); // NOI18N

        javax.swing.GroupLayout pdf1PanelLayout = new javax.swing.GroupLayout(pdf1Panel);
        pdf1Panel.setLayout(pdf1PanelLayout);
        pdf1PanelLayout.setHorizontalGroup(
            pdf1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pd1Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pdf1TitleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pdf1PanelLayout.setVerticalGroup(
            pdf1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdf1PanelLayout.createSequentialGroup()
                .addComponent(pdf1TitleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pd1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pdf1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pdf1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pdf1TitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdf1TitleButtonActionPerformed
        // TODO add your handling code here:
        Main.pdf2TextCopied = false;
        Main.pdf3TextCopied = false;
        Main.pdf1TextCopied = true;        
    }//GEN-LAST:event_pdf1TitleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pd1Text;
    private javax.swing.JPanel pdf1Panel;
    private javax.swing.JButton pdf1TitleButton;
    // End of variables declaration//GEN-END:variables
}
