/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop;

/**
 *
 * @author haris
 */
public class PDF2 extends javax.swing.JInternalFrame {
    
    public static String pdf2Text = "Breaking the Disposable Technology Paradigm: Opportunities for Sustainable Interaction Design for Mobile Phones\n";

    /**
     * Creates new form PDF1
     */
    public PDF2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pdf2Panel = new javax.swing.JPanel();
        pdf2TitleButton = new javax.swing.JButton();
        pd2Text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("pdf2");

        pdf2Panel.setBackground(new java.awt.Color(255, 255, 255));

        pdf2TitleButton.setBackground(new java.awt.Color(255, 255, 255));
        pdf2TitleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/images/pdf2Title.png"))); // NOI18N
        pdf2TitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdf2TitleButtonActionPerformed(evt);
            }
        });

        pd2Text.setBackground(new java.awt.Color(255, 255, 255));
        pd2Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/images/pdf2Text.png"))); // NOI18N
        pd2Text.setToolTipText("");

        javax.swing.GroupLayout pdf2PanelLayout = new javax.swing.GroupLayout(pdf2Panel);
        pdf2Panel.setLayout(pdf2PanelLayout);
        pdf2PanelLayout.setHorizontalGroup(
            pdf2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pd2Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pdf2TitleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pdf2PanelLayout.setVerticalGroup(
            pdf2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdf2PanelLayout.createSequentialGroup()
                .addComponent(pdf2TitleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pd2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pdf2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pdf2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pdf2TitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdf2TitleButtonActionPerformed
        // TODO add your handling code here:
        Main.pdf1TextCopied = false;
        Main.pdf3TextCopied = false;
        Main.pdf2TextCopied = true;
        
        Main.recall = false;
        Main.fe.repeatButton.setVisible(false);
    }//GEN-LAST:event_pdf2TitleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pd2Text;
    private javax.swing.JPanel pdf2Panel;
    private javax.swing.JButton pdf2TitleButton;
    // End of variables declaration//GEN-END:variables
}
