/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop;

/**
 *
 * @author haris
 */
public class PDF3 extends javax.swing.JInternalFrame {
    
    public static String pdf2Text = "An Examination of Daily Information Needs and Sharing Opportunities";

    /**
     * Creates new form PDF1
     */
    public PDF3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pdf3Panel = new javax.swing.JPanel();
        pdf3TitleButton = new javax.swing.JButton();
        pd3Text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("pdf3");

        pdf3Panel.setBackground(new java.awt.Color(255, 255, 255));

        pdf3TitleButton.setBackground(new java.awt.Color(255, 255, 255));
        pdf3TitleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/images/pdf3Title.png"))); // NOI18N
        pdf3TitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdf3TitleButtonActionPerformed(evt);
            }
        });

        pd3Text.setBackground(new java.awt.Color(255, 255, 255));
        pd3Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/images/pdf3Text.png"))); // NOI18N
        pd3Text.setToolTipText("");

        javax.swing.GroupLayout pdf3PanelLayout = new javax.swing.GroupLayout(pdf3Panel);
        pdf3Panel.setLayout(pdf3PanelLayout);
        pdf3PanelLayout.setHorizontalGroup(
            pdf3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pd3Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pdf3TitleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pdf3PanelLayout.setVerticalGroup(
            pdf3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdf3PanelLayout.createSequentialGroup()
                .addComponent(pdf3TitleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pd3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pdf3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pdf3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pdf3TitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdf3TitleButtonActionPerformed
        // TODO add your handling code here:
        Main.pdf1TextCopied = false;
        Main.pdf2TextCopied = false;
        Main.pdf3TextCopied = true;
    }//GEN-LAST:event_pdf3TitleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pd3Text;
    private javax.swing.JPanel pdf3Panel;
    private javax.swing.JButton pdf3TitleButton;
    // End of variables declaration//GEN-END:variables
}
